# export CUDA_NVCC_EXECUTABLE=/usr/local/cuda-11.3/bin/nvcc
# export CUDA_HOME=/usr/local/cuda-11.3/
# export LIBRARY_PATH=/usr/local/cuda-11.3/lib64/
# USE_CUDA=ON USE_CUDNN=ON DEBUG=ON USE_NCCL=ON USE_OPENMP=ON USE_SYSTEM_NCCL=ON USE_KINETO=OFF USE_MKLDNN=OFF USE_FBGEMM=OFF BUILD_SPLIT_CUDA=ON TORCH_CUDA_ARCH_LIST="7.0 7.5 8.0" VERBOSE=1 python setup.py install

cd build
/usr/bin/c++ -DHAVE_MALLOC_USABLE_SIZE=1 -DHAVE_MMAP=1 -DHAVE_SHM_OPEN=1 -DHAVE_SHM_UNLINK=1 -DMINIZ_DISABLE_ZIP_READER_CRC32_CHECKS -DONNXIFI_ENABLE_EXT=1 -DONNX_ML=1 -DONNX_NAMESPACE=onnx_torch -DUSE_EXTERNAL_MZCRC -D_FILE_OFFSET_BITS=64 -Dc10_cuda_EXPORTS -I/root/pytorch/pytorch/build/aten/src -I/root/pytorch/pytorch/aten/src -I/root/pytorch/pytorch/build -I/root/pytorch/pytorch -I/root/pytorch/pytorch/cmake/../third_party/benchmark/include -I/root/pytorch/pytorch/cmake/../third_party/cudnn_frontend/include -I/root/pytorch/pytorch/third_party/onnx -I/root/pytorch/pytorch/build/third_party/onnx -I/root/pytorch/pytorch/third_party/foxi -I/root/pytorch/pytorch/build/third_party/foxi -I/root/pytorch/pytorch/c10/cuda/../.. -I/root/pytorch/pytorch/c10/.. -isystem /root/pytorch/pytorch/build/third_party/gloo -isystem /root/pytorch/pytorch/cmake/../third_party/gloo -isystem /root/pytorch/pytorch/cmake/../third_party/googletest/googlemock/include -isystem /root/pytorch/pytorch/cmake/../third_party/googletest/googletest/include -isystem /root/pytorch/pytorch/third_party/protobuf/src -isystem /root/pytorch/pytorch/third_party/gemmlowp -isystem /root/pytorch/pytorch/third_party/neon2sse -isystem /root/pytorch/pytorch/third_party/XNNPACK/include -isystem /root/pytorch/pytorch/cmake/../third_party/eigen -isystem /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi -isystem /usr/lib/x86_64-linux-gnu/openmpi/include -isystem /usr/local/cuda-11.3/include -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow -g -fno-omit-frame-pointer -O0 -std=gnu++14 -fPIC -DCAFFE2_USE_GLOO -DTH_HAVE_THREAD -DC10_CUDA_BUILD_MAIN_LIB -fvisibility=hidden -MD -MT c10/cuda/CMakeFiles/c10_cuda.dir/CUDACachingAllocator.cpp.o -MF c10/cuda/CMakeFiles/c10_cuda.dir/CUDACachingAllocator.cpp.o.d -o c10/cuda/CMakeFiles/c_cuda.dir/CUDACachingAllocator.cpp.o -c /root/pytorch/pytorch/c10/cuda/CUDACachingAllocator.cpp
/usr/bin/c++ -fPIC -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow -g -fno-omit-frame-pointer -O0  -Wl,--no-as-needed -rdynamic -shared -Wl,-soname,libc10_cuda.so -o lib/libc10_cuda.so c10/cuda/CMakeFiles/c10_cuda.dir/CUDAStream.cpp.o c10/cuda/CMakeFiles/c10_cuda.dir/CUDAFunctions.cpp.o c10/cuda/CMakeFiles/c10_cuda.dir/CUDAMiscFunctions.cpp.o c10/cuda/CMakeFiles/c10_cuda.dir/CUDACachingAllocator.cpp.o c10/cuda/CMakeFiles/c10_cuda.dir/impl/CUDAGuardImpl.cpp.o c10/cuda/CMakeFiles/c10_cuda.dir/impl/CUDATest.cpp.o  -Wl,-rpath,/root/pytorch/pytorch/build/lib:/usr/local/cuda-11.3/lib64:lib/libc10.so  /usr/local/cuda-11.3/lib64/libcudart.so

cp lib/libc10_cuda.so /usr/local/lib/python3.9/site-packages/torch/lib/
